
name: Manually Triggered
on:
  workflow_dispatch:
    inputs:
      string:
        description: Image Tag
        type: string
        required: true
        default: "latest"
      number:
        description: Number Of Containers
        default: 1
        type: number
      option:
        description: "Deployment Type"
        required: true
        default: "Green Deployment"
        type: choice
        options:
          - Prod Deployment
          - Green Deployment
#      boolean:
#        description: Switch LB
#        required: false
#        type: boolean
      environment:
        description: "Environment"
        type: environment
        required: true

jobs:
  log-info:
    runs-on: ubuntu-latest
    steps:
      - run: echo $GITHUB_REF
      - run: |
          echo "String: ${{ inputs.string }}"
          echo "Number: ${{ inputs.number }}"
          echo "Option: ${{ inputs.option }}"
#          echo "Boolean: ${{ inputs.boolean }}"
#          echo "Environment: ${{ inputs.environment }}"
